// <auto-generated />
using System;
using CatOs.Infrastructure.AppContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatOs.ApiHost.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatOs.Core.DbModels.SKU.SkuComponents", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentUuid")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SkuUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("ComponentUuid");

                    b.HasIndex("SkuUuid");

                    b.ToTable("SkuComponents");
                });

            modelBuilder.Entity("CatOs.Core.DbModels.SKU.SkuDb", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdenTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenTable"));

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("Skus");
                });

            modelBuilder.Entity("CatOs.Core.DbModels.Stock.Components", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdenTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenTable"));

                    b.Property<double>("QuantityInStock")
                        .HasColumnType("double precision");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("integer");

                    b.Property<string>("UnitPrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CatOs.Core.DbModels.SKU.SkuComponents", b =>
                {
                    b.HasOne("CatOs.Core.DbModels.Stock.Components", "Components")
                        .WithMany()
                        .HasForeignKey("ComponentUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatOs.Core.DbModels.SKU.SkuDb", "Sku")
                        .WithMany("SkuComponents")
                        .HasForeignKey("SkuUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Components");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("CatOs.Core.DbModels.SKU.SkuDb", b =>
                {
                    b.Navigation("SkuComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
